sudo: required
services:
  - docker

before_install:
  - docker build -t jtfetzer/docker-react -f Dockerfile.dev .

script:
  - docker run jtfetzer/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-us-west-1-844365218476"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"